apiVersion: v1
kind: ConfigMap
metadata:
  name: prices-api-config
  labels:
    app.kubernetes.io/name: prices-microservice
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: prices-microservice
    app.kubernetes.io/version: "0.0.1"
data:
  SPRING_CACHE_TYPE: redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  PRICE_CACHE_TTL: 10m
  REDIS_CONNECT_TIMEOUT: 250ms
  REDIS_TIMEOUT: 250ms
  MANAGEMENT_HEALTH_REDIS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_LIVENESS_INCLUDE: livenessState
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE: readinessState
  SERVER_SHUTDOWN: graceful
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: 20s
