CREATE TABLE prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brand_id BIGINT NOT NULL,
    start_date TIMESTAMP(0) NOT NULL,
    end_date TIMESTAMP(0) NOT NULL,
    price_list BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    priority INTEGER NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    curr VARCHAR(3) NOT NULL,
    CONSTRAINT pk_prices PRIMARY KEY (id),
    CONSTRAINT ck_prices_brand_id_positive CHECK (brand_id > 0),
    CONSTRAINT ck_prices_product_id_positive CHECK (product_id > 0),
    CONSTRAINT ck_prices_price_list_positive CHECK (price_list > 0),
    CONSTRAINT ck_prices_priority_non_negative CHECK (priority >= 0),
    CONSTRAINT ck_prices_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_prices_date_range CHECK (start_date <= end_date),
    CONSTRAINT ck_prices_currency_format CHECK (REGEXP_LIKE(curr, '^[A-Z]{3}$'))
);

CREATE INDEX idx_prices_applicable
    ON prices (brand_id, product_id, start_date, end_date, priority DESC);
